"use strict";let ctm=document.querySelectorAll(".ctm");let ctmMulti=document.querySelectorAll(".ctm-multi");let ctmBubble=document.querySelectorAll(".ctm-bubble");let currentTime=document.querySelector(".current-time");let ctmUserAvailability=document.querySelectorAll(".ctmUserAvailability");let ctmSendMessage=document.querySelector(".ctm__send-message");let ctmMultiPopupContent=document.querySelector(".ctm-multi__popup--content");let user=document.querySelector(".user");let today=new Date();if(currentTime!==null){let time=today.getHours()+":"+today.getMinutes()+":"+today.getSeconds();currentTime.innerText=time;}
const openChatBtn=()=>{ctm.forEach((item)=>{item.classList?.toggle("ctm-show");});ctmMulti.forEach((item)=>{item.classList?.toggle("ctm-show");});};ctmBubble.forEach((item)=>{item.addEventListener("click",openChatBtn);});function is_available(available,now){let is_available=false;let almost_available=false;for(let key in available){if(available.hasOwnProperty(key)){if(get_day_of_week(key)==now.day()){let start=moment(available[key].split("-")[0],"HH:mm");let end=moment(available[key].split("-")[1],"HH:mm");if(moment().isAfter(start)&&moment().isBefore(end)){is_available=true;}else if(now.isBefore(start)){almost_available=true;}}}}
return{is_available:is_available,almost_available:almost_available};}
function get_day_of_week(name){name=name.toLowerCase();if(name=="sunday"){return 0;}else if(name=="monday"){return 1;}else if(name=="tuesday"){return 2;}else if(name=="wednesday"){return 3;}else if(name=="thursday"){return 4;}else if(name=="friday"){return 5;}else if(name=="saturday"){return 6;}}
const searchInfo=ctmMultiPopupContent?.getAttribute("data-search");const isGrid=document.querySelector(".ctm-multi")?.classList.contains("ctm-grid");if(ctmUserAvailability!==undefined){if(searchInfo==="true"){ctmMultiPopupContent.classList.add("ctm-search");}
if(ctmUserAvailability.length>3&&!isGrid){ctmMultiPopupContent.classList.add("ctm-scroll");}
if(ctmUserAvailability.length>4&&isGrid){ctmMultiPopupContent.classList.add("ctm-scroll");}
ctmUserAvailability.forEach((item)=>{const availableTimes=item.getAttribute("data-ctmUserAvailability");const timezone=item.getAttribute("data-timezone");let now=timezone?moment().tz(timezone):moment();let available=is_available(JSON.parse(availableTimes),now);if(available.is_available||availableTimes==null){ctmUserAvailability.forEach((item)=>{const availableTime=item.getAttribute("data-ctmUserAvailability");if(availableTime===availableTimes){item.classList.add("avatar-active");item.classList.remove("avatar-inactive");}});}else{ctmUserAvailability.forEach((item)=>{const availableTime=item.getAttribute("data-ctmUserAvailability");if(availableTime===availableTimes){item.classList.add("avatar-inactive");item.setAttribute("disabled","");item.classList.remove("avatar-active");}});}});}
function searchUser(){var searchKeyword,i,txtValue;let input=document.getElementById("search-input");let filter=input.value.toUpperCase();let multiUser=document.getElementById("multi-user");let user=multiUser.getElementsByClassName("user");for(i=0;i<user.length;i++){searchKeyword=user[i].getElementsByClassName("user__info--name")[0];txtValue=searchKeyword.textContent||searchKeyword.innerText;if(txtValue.toUpperCase().indexOf(filter)>-1){user[i].style.display="";}else{user[i].style.display="none";}}}
let mcButtons=document.querySelectorAll(".mcButtons");if(mcButtons!==undefined){mcButtons.forEach((item)=>{const availableTimes=item.getAttribute("data-ctmTime");const timezone=item.getAttribute("data-timezone");let now=timezone?moment().tz(timezone):moment();let available=is_available(JSON.parse(availableTimes),now);if(available.is_available){mcButtons.forEach((item)=>{const availableTime=item.getAttribute("data-ctmTime");if(availableTime===availableTimes){item.classList.add("avatar-active");}});}else{mcButtons.forEach((item)=>{const availableTime=item.getAttribute("data-ctmTime");if(availableTime===availableTimes){item.classList.add("avatar-inactive");}});}});}
const chatAvailability=document.querySelector(".chat-availability");if(chatAvailability){const chatAvailableTime=chatAvailability.getAttribute("data-availability");if(chatAvailableTime!==undefined){let now=moment();let available=is_available(JSON.parse(chatAvailableTime),now);if(available.is_available||chatAvailableTime==null){chatAvailability.classList.add("avatar-active");}else{chatAvailability.classList.add("avatar-inactive");}}}
let value=document.querySelector(".mailtoui").getAttribute("href");let subject=document.getElementById("subject");let message=document.getElementById("message");if(subject){subject.addEventListener("keyup",(event)=>{changeHrefValue(subject);});}
if(message){message.addEventListener("keyup",(event)=>{changeHrefValue(message);});}
const changeHrefValue=()=>{let subjectValue=subject.value;let messageValue=message.value;let inputChangeValue={subjectText:subjectValue,bodyText:messageValue,};let changeValue=value.replace(/subjectText|bodyText/gi,function(matched){return inputChangeValue[matched];});document.querySelector(".mailtoui").href=changeValue;};;